### ISSUE TITLE
Check why this test error occured in travis

### ISSUE THREAD

**Issue by pLeminoq** [openbase/bco.manager#12]
<pre>
23:14:36.789 [main] [1;31mERROR[0;39m [36mo.o.b.m.d.t.r.u.BrightnessSensorRemoteTest[0;39m â•â•â• org.openbase.bco.dal.lib.layer.unit.UnitRemote.getConfig()Lrst/domotic/unit/UnitConfigType$UnitConfig;
23:14:36.789 [main] [1;31mERROR[0;39m [36mo.o.b.m.d.t.r.u.BrightnessSensorRemoteTest[0;39m =====================================
23:14:36.789 [main] [1;31mERROR[0;39m [36mo.o.b.m.d.t.r.u.BrightnessSensorRemoteTest[0;39m org.openbase.bco.dal.lib.layer.unit.UnitRemote.getConfig()Lrst/domotic/unit/UnitConfigType$UnitConfig;
java.lang.NoSuchMethodError: org.openbase.bco.dal.lib.layer.unit.UnitRemote.getConfig()Lrst/domotic/unit/UnitConfigType$UnitConfig;
	at org.openbase.bco.dal.lib.layer.unit.UnitRemote.isEnabled(UnitRemote.java:89)
	at org.openbase.bco.dal.remote.unit.AbstractUnitRemote.activate(AbstractUnitRemote.java:227)
	at org.openbase.bco.manager.device.test.remote.unit.BrightnessSensorRemoteTest.setUpClass(BrightnessSensorRemoteTest.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
</pre>

**Comment by DivineThreepwood** [comment]
After moving the isEnabled() Method from default interface implementation to AbstractUnitController implementation this Exception did not occurs again. This seems to be a java vm or class loader bug. So calling default implementations via other default implementations seems to trigger this exception.

However, this solves the problem.
