### ISSUE TITLE
Root location not available during unit tests.

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.manager#14]
Sometime the root location is not available during the unit tests which is really strange because the root consistency check should guarantee its availability after mock registry startup.

<pre>
12:57:39.495 [main] ERROR o.o.b.m.s.t.r.s.SceneRemoteTest ═╦═⚀ Could not register scene!
12:57:39.495 [main] ERROR o.o.b.m.s.t.r.s.SceneRemoteTest  ╚══╦═⚀ Context[Unit[44075e12-3f07-4ea3-b711-67c7cd7027d7|Paradise]] is not available!
12:57:39.495 [main] ERROR o.o.b.m.s.t.r.s.SceneRemoteTest     ╚══╦═⚀ Context[UnitRemote[44075e12-3f07-4ea3-b711-67c7cd7027d7]] is not available!
12:57:39.495 [main] ERROR o.o.b.m.s.t.r.s.SceneRemoteTest        ╚══╦═⚀ Could not initialize class org.openbase.bco.dal.remote.unit.location.LocationRemote!
12:57:39.495 [main] ERROR o.o.b.m.s.t.r.s.SceneRemoteTest           ╚════⚀ Entry[b495a2f0-fe76-46da-abd4-a5671c4c3820]] is not available! Nearest neighbor is UnitConfig[PH_Hue_E27_Device] or UnitConfig[PH_Hue_E27_Device_BORROWED].
12:57:39.496 [main] ERROR o.o.b.m.s.t.r.s.SceneRemoteTest =====================================
12:57:39.498 [main] ERROR o.o.b.m.s.t.r.s.SceneRemoteTest Could not register scene!
org.openbase.jul.exception.CouldNotPerformException: Could not register scene!
	at org.openbase.bco.manager.scene.test.remote.scene.SceneRemoteTest.registerScenes(SceneRemoteTest.java:262)
	at org.openbase.bco.manager.scene.test.remote.scene.SceneRemoteTest.setUpClass(SceneRemoteTest.java:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: org.openbase.jul.exception.NotAvailableException: Context[Unit[44075e12-3f07-4ea3-b711-67c7cd7027d7|Paradise]] is not available!
	at org.openbase.bco.dal.remote.unit.Units.getUnit(Units.java:376)
	at org.openbase.bco.dal.remote.unit.Units.getUnit(Units.java:396)
	at org.openbase.bco.manager.scene.test.remote.scene.SceneRemoteTest.registerScenes(SceneRemoteTest.java:223)
	... 18 common frames omitted
Caused by: org.openbase.jul.exception.NotAvailableException: Context[UnitRemote[44075e12-3f07-4ea3-b711-67c7cd7027d7]] is not available!
	at org.openbase.bco.dal.remote.unit.Units.getUnitRemote(Units.java:308)
	at org.openbase.bco.dal.remote.unit.Units.getUnit(Units.java:374)
	... 20 common frames omitted
Caused by: org.openbase.jul.exception.InitializationException: Could not initialize class org.openbase.bco.dal.remote.unit.location.LocationRemote!
	at org.openbase.jul.extension.rsb.com.AbstractConfigurableRemote.init(AbstractConfigurableRemote.java:79)
	at org.openbase.jul.extension.rsb.com.AbstractConfigurableRemote.init(AbstractConfigurableRemote.java:46)
	at org.openbase.bco.dal.remote.unit.UnitRemoteFactoryImpl.newInitializedInstance(UnitRemoteFactoryImpl.java:219)
	at org.openbase.bco.dal.remote.unit.Units.getUnitRemote(Units.java:288)
	... 21 common frames omitted
Caused by: org.openbase.jul.exception.NotAvailableException: Entry[b495a2f0-fe76-46da-abd4-a5671c4c3820]] is not available! Nearest neighbor is UnitConfig[PH_Hue_E27_Device] or UnitConfig[PH_Hue_E27_Device_BORROWED].
	at org.openbase.jul.storage.registry.AbstractRegistry.get(AbstractRegistry.java:319)
	at org.openbase.jul.storage.registry.RemoteRegistry.getMessage(RemoteRegistry.java:78)
	at org.openbase.bco.registry.unit.remote.UnitRegistryRemote.getUnitConfigById(UnitRegistryRemote.java:229)
	at org.openbase.bco.dal.remote.service.ServiceRemoteManager.applyConfigUpdate(ServiceRemoteManager.java:112)
	at org.openbase.bco.dal.remote.unit.location.LocationRemote.applyConfigUpdate(LocationRemote.java:111)
	at org.openbase.bco.dal.remote.unit.location.LocationRemote.applyConfigUpdate(LocationRemote.java:68)
	at org.openbase.jul.extension.rsb.com.AbstractConfigurableRemote.init(AbstractConfigurableRemote.java:76)
	... 24 common frames omitted
</pre>

**Comment by DivineThreepwood** [comment]
Bug is already fixed by the new virtual registry synchronization during startup.
