### ISSUE TITLE
Location Controller are not reloaded after initial sync failures

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.manager#38]
<pre>
01:07:07.689 [pool-1-thread-3] ERROR o.o.b.m.l.c.LocationManagerController$1 ═╦═⚀ Initial sync failed!
01:07:07.689 [pool-1-thread-3] ERROR o.o.b.m.l.c.LocationManagerController$1  ╚══╦═⚀ Entry registry sync failed!
01:07:07.690 [pool-1-thread-3] ERROR o.o.b.m.l.c.LocationManagerController$1     ╚══╦═⚄ Could not sync all entries!
01:07:07.690 [pool-1-thread-3] ERROR o.o.b.m.l.c.LocationManagerController$1        ╚══╦═⚄ Could not register 2 entries!
01:07:07.690 [pool-1-thread-3] ERROR o.o.b.m.l.c.LocationManagerController$1           ╠══╦═⚀ Could not instantiate LocationControllerImpl[ddc5097e-1018-443d-b288-e27e3a247e5d]!
01:07:07.690 [pool-1-thread-3] ERROR o.o.b.m.l.c.LocationManagerController$1           ║  ╚══╦═⚀ Could not initialize class org.openbase.bco.manager.location.core.LocationControllerImpl!
01:07:07.690 [pool-1-thread-3] ERROR o.o.b.m.l.c.LocationManagerController$1           ║     ╚══╦═⚀ Could not initialize class org.openbase.bco.manager.location.core.LocationControllerImpl!
01:07:07.690 [pool-1-thread-3] ERROR o.o.b.m.l.c.LocationManagerController$1           ║        ╚════⚀ Entry[2c95255e-a491-46d7-a6a6-f66d5e6c2d3b]] is not available! Nearest neighbor is UnitC
onfig[SportsToLivingReedSwitch] or UnitConfig[CeilingWindowLamp].
01:07:07.690 [pool-1-thread-3] ERROR o.o.b.m.l.c.LocationManagerController$1           ╚══╦═⚀ Could not instantiate LocationControllerImpl[f0a71f71-1463-41e3-9c9a-25a02a536001]!
01:07:07.690 [pool-1-thread-3] ERROR o.o.b.m.l.c.LocationManagerController$1              ╚══╦═⚀ Could not initialize class org.openbase.bco.manager.location.core.LocationControllerImpl!
01:07:07.690 [pool-1-thread-3] ERROR o.o.b.m.l.c.LocationManagerController$1                 ╚══╦═⚀ Could not initialize class org.openbase.bco.manager.location.core.LocationControllerImpl!
01:07:07.691 [pool-1-thread-3] ERROR o.o.b.m.l.c.LocationManagerController$1                    ╚════⚀ Entry[2c95255e-a491-46d7-a6a6-f66d5e6c2d3b]] is not available! Nearest neighbor is UnitConfig[SportsToLivingReedSwitch] or UnitConfig[CeilingWindowLamp].
01:07:07.691 [pool-1-thread-3] ERROR o.o.b.m.l.c.LocationManagerController$1 =====================================
01:07:07.691 [pool-1-thread-3] ERROR o.o.b.m.l.c.LocationManagerController$1 Initial sync failed!
org.openbase.jul.exception.CouldNotPerformException: Initial sync failed!
        at org.openbase.jul.storage.registry.RegistrySynchronizer.activate(RegistrySynchronizer.java:103)
        at org.openbase.bco.manager.location.core.LocationManagerController.activate(LocationManagerController.java:112)
        at org.openbase.bco.registry.lib.launch.AbstractLauncher.launch(AbstractLauncher.java:180)
        at org.openbase.bco.registry.lib.launch.AbstractLauncher$1.call(AbstractLauncher.java:322)
        at org.openbase.bco.registry.lib.launch.AbstractLauncher$1.call(AbstractLauncher.java:318)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.openbase.jul.exception.CouldNotPerformException: Entry registry sync failed!
        at org.openbase.jul.storage.registry.RegistrySynchronizer.internalSync(RegistrySynchronizer.java:224)
        at org.openbase.jul.storage.registry.RegistrySynchronizer.activate(RegistrySynchronizer.java:101)
        ... 8 common frames omitted
Caused by: org.openbase.jul.exception.MultiException: Could not sync all entries!
        at org.openbase.jul.exception.MultiException.checkAndThrow(MultiException.java:62)
        at org.openbase.jul.storage.registry.RegistrySynchronizer.internalSync(RegistrySynchronizer.java:222)
        ... 9 common frames omitted
Caused by: org.openbase.jul.exception.MultiException: Could not register 2 entries!
        at org.openbase.jul.exception.MultiException.checkAndThrow(MultiException.java:62)
        at org.openbase.jul.storage.registry.RegistrySynchronizer.internalSync(RegistrySynchronizer.java:218)
        ... 9 common frames omitted
Caused by: org.openbase.jul.exception.InstantiationException: Could not instantiate LocationControllerImpl[ddc5097e-1018-443d-b288-e27e3a247e5d]!
        at org.openbase.bco.manager.location.core.LocationFactoryImpl.newInstance(LocationFactoryImpl.java:58)
        at org.openbase.bco.manager.location.core.LocationFactoryImpl.newInstance(LocationFactoryImpl.java:36)
        at org.openbase.jul.storage.registry.RegistrySynchronizer.register(RegistrySynchronizer.java:234)
        at org.openbase.jul.storage.registry.ActivatableEntryRegistrySynchronizer.register(ActivatableEntryRegistrySynchronizer.java:58)
        at org.openbase.jul.storage.registry.RegistrySynchronizer.internalSync(RegistrySynchronizer.java:166)
        ... 9 common frames omitted
Caused by: org.openbase.jul.exception.InitializationException: Could not initialize class org.openbase.bco.manager.location.core.LocationControllerImpl!
        at org.openbase.bco.dal.lib.layer.unit.AbstractUnitController.init(AbstractUnitController.java:167)
        at org.openbase.bco.manager.location.core.LocationControllerImpl.init(LocationControllerImpl.java:135)
        at org.openbase.bco.manager.location.core.LocationFactoryImpl.newInstance(LocationFactoryImpl.java:55)
        ... 13 common frames omitted
Caused by: org.openbase.jul.exception.InitializationException: Could not initialize class org.openbase.bco.manager.location.core.LocationControllerImpl!
        at org.openbase.jul.extension.rsb.com.AbstractConfigurableController.init(AbstractConfigurableController.java:74)
        at org.openbase.bco.dal.lib.layer.unit.AbstractUnitController.init(AbstractUnitController.java:165)
        ... 15 common frames omitted
Caused by: org.openbase.jul.exception.NotAvailableException: Entry[2c95255e-a491-46d7-a6a6-f66d5e6c2d3b]] is not available! Nearest neighbor is UnitConfig[SportsToLivingReedSwitch] or UnitConfig[CeilingWindowLamp].
        at org.openbase.jul.storage.registry.AbstractRegistry.get(AbstractRegistry.java:333)
        at org.openbase.jul.storage.registry.RemoteRegistry.getMessage(RemoteRegistry.java:78)
        at org.openbase.bco.registry.unit.remote.UnitRegistryRemote.getUnitConfigById(UnitRegistryRemote.java:241)
        at org.openbase.bco.dal.remote.service.ServiceRemoteManager.applyConfigUpdate(ServiceRemoteManager.java:113)
        at org.openbase.bco.manager.location.core.LocationControllerImpl.applyConfigUpdate(LocationControllerImpl.java:142)
        at org.openbase.bco.manager.location.core.LocationControllerImpl.applyConfigUpdate(LocationControllerImpl.java:75)
        at org.openbase.jul.extension.rsb.com.AbstractConfigurableController.init(AbstractConfigurableController.java:71)
        ... 16 common frames omitted
01:07:07.693 [pool-1-thread-3] ERROR o.o.b.m.l.c.LocationManagerController$1 =====================================
</pre>

results in:

<pre>
01:07:57.908 [pool-1-thread-190] WARN  o.o.b.d.r.u.l.LocationRemote =====================================
01:07:57.908 [pool-1-thread-190] WARN  o.o.b.d.r.u.l.LocationRemote Controller[/home/] does not respond!  Next retry timeout in 15 sec.
01:08:00.329 [pool-1-thread-105] WARN  o.o.b.d.r.u.l.LocationRemote ═══⚀ TimeoutException
01:08:00.329 [pool-1-thread-105] WARN  o.o.b.d.r.u.l.LocationRemote =====================================
01:08:00.329 [pool-1-thread-105] WARN  o.o.b.d.r.u.l.LocationRemote Controller[/home/kitchen/] does not respond!  Next retry timeout in 16 sec.
01:08:13.392 [pool-1-thread-190] WARN  o.o.b.d.r.u.l.LocationRemote ═══⚀ TimeoutException
01:08:13.392 [pool-1-thread-190] WARN  o.o.b.d.r.u.l.LocationRemote =====================================
01:08:13.392 [pool-1-thread-190] WARN  o.o.b.d.r.u.l.LocationRemote Controller[/home/] does not respond!  Next retry timeout in 18 sec.
01:08:16.493 [pool-1-thread-105] WARN  o.o.b.d.r.u.l.LocationRemote ═══⚀ TimeoutException
01:08:16.493 [pool-1-thread-105] WARN  o.o.b.d.r.u.l.LocationRemote =====================================
01:08:16.493 [pool-1-thread-105] WARN  o.o.b.d.r.u.l.LocationRemote Controller[/home/kitchen/] does not respond!  Next retry timeout in 19 sec.

01:08:32.289 [pool-1-thread-190] WARN  o.o.b.d.r.u.l.LocationRemote ═══⚀ TimeoutException
01:08:32.289 [pool-1-thread-190] WARN  o.o.b.d.r.u.l.LocationRemote =====================================
01:08:32.289 [pool-1-thread-190] WARN  o.o.b.d.r.u.l.LocationRemote Controller[/home/] does not respond!  Next retry timeout in 23 sec.
01:08:36.078 [pool-1-thread-105] WARN  o.o.b.d.r.u.l.LocationRemote ═══⚀ TimeoutException
01:08:36.078 [pool-1-thread-105] WARN  o.o.b.d.r.u.l.LocationRemote =====================================
01:08:36.078 [pool-1-thread-105] WARN  o.o.b.d.r.u.l.LocationRemote Controller[/home/kitchen/] does not respond!  Next retry timeout in 23 sec.
01:08:55.530 [pool-1-thread-190] WARN  o.o.b.d.r.u.l.LocationRemote ═══⚀ TimeoutException
01:08:55.530 [pool-1-thread-190] WARN  o.o.b.d.r.u.l.LocationRemote =====================================
01:08:55.530 [pool-1-thread-190] WARN  o.o.b.d.r.u.l.LocationRemote Controller[/home/] does not respond!  Next retry timeout in 28 sec.
01:08:59.992 [pool-1-thread-105] WARN  o.o.b.d.r.u.l.LocationRemote ═══⚀ TimeoutException
01:08:59.992 [pool-1-thread-105] WARN  o.o.b.d.r.u.l.LocationRemote =====================================
01:08:59.992 [pool-1-thread-105] WARN  o.o.b.d.r.u.l.LocationRemote Controller[/home/kitchen/] does not respond!  Next retry timeout in 29 sec.
01:09:24.226 [pool-1-thread-190] WARN  o.o.b.d.r.u.l.LocationRemote ═══⚀ TimeoutException
01:09:24.226 [pool-1-thread-190] WARN  o.o.b.d.r.u.l.LocationRemote =====================================
01:09:24.226 [pool-1-thread-190] WARN  o.o.b.d.r.u.l.LocationRemote Controller[/home/] does not respond!  Next retry timeout in 30 sec.
</pre>

**Comment by pLeminoq** [comment]
This should be fixed with commit openbase/bco.dal@e1eec94df0f448f7fb4566f1b441a1e53e7229b3. Now the not available exception is only printed and not thrown. This way the location controller will start regardless.
