### ISSUE TITLE
New Runtime Exception on Unit Test

### ISSUE THREAD

**Issue by tsafs** [openbase/bco.manager#42]
```
testRegisterDeviceWhileRunning
12:27:57.022 [pool-1-thread-51] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register DeviceClass[TestRegisterDeviceWhileRunnint]...
12:27:57.022 [pool-1-thread-51] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry 3% of max consistency checks passed of DeviceClassRegistry after 1 applied modifications.
12:27:57.030 [pool-1-thread-56] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register UnitConfig[RunningDevice]...
12:27:57.033 [pool-1-thread-56] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry 0% of max consistency checks passed of DeviceConfigRegistry after 1 applied modifications.
12:27:57.035 [pool-1-thread-56] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Register UnitConfig[c7aa2763-249c-443f-8159-62400b0603b7]...
12:27:57.052 [pool-1-thread-56] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry 0% of max consistency checks passed of DalUnitConfigRegistry after 1 applied modifications.
12:27:57.070 [pool-2-thread-10] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry 100% consistency checks passed of ConnectionConfigRegistry after 5 applied modifications.
12:27:57.071 [pool-1-thread-56] INFO  o.o.b.r.u.c.p.PublishDalUnitTransformationRegistryPlugin Publish Paradise to RunningDevice
12:27:57.071 [pool-2-thread-7] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry 100% consistency checks passed of LocationConfigRegistry after 1 applied modifications.
12:27:57.072 [pool-1-thread-56] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry 1% of max consistency checks passed of LocationConfigRegistry after 1 applied modifications.
12:27:57.073 [pool-1-thread-56] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry Update UnitConfig[RunningDevice]...
12:27:57.073 [pool-1-thread-56] INFO  o.o.b.r.u.c.p.PublishDeviceTransformationRegistryPlugin Publish Paradise to RunningDevice
12:27:57.122 [pool-2-thread-2] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry 100% consistency checks passed of DeviceClassRegistry after 2 applied modifications.
12:27:57.133 [pool-2-thread-8] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry 100% consistency checks passed of DeviceConfigRegistry after 6 applied modifications.
12:27:57.153 [pool-2-thread-8] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry 100% consistency checks passed of DalUnitConfigRegistry after 13 applied modifications.
12:27:57.160 [Thread-12176] ERROR o.o.j.s.RecurrenceEventFilter ═══⚀ NullPointerException
12:27:57.160 [Thread-12176] ERROR o.o.j.s.RecurrenceEventFilter =====================================
12:27:57.162 [Thread-12176] ERROR o.o.j.s.RecurrenceEventFilter NullPointerException
java.lang.NullPointerException: null
	at org.openbase.jul.extension.rsb.com.RSBCommunicationService.activate(RSBCommunicationService.java:325)
	at org.openbase.bco.dal.lib.layer.unit.AbstractHostUnitController.activate(AbstractHostUnitController.java:96)
	at org.openbase.jul.storage.registry.ActivatableEntryRegistrySynchronizer.register(ActivatableEntryRegistrySynchronizer.java:61)
	at org.openbase.jul.storage.registry.RegistrySynchronizer.internalSync(RegistrySynchronizer.java:169)
	at org.openbase.jul.storage.registry.RegistrySynchronizer.access$000(RegistrySynchronizer.java:54)
	at org.openbase.jul.storage.registry.RegistrySynchronizer$1.relay(RegistrySynchronizer.java:77)
	at org.openbase.jul.schedule.RecurrenceEventFilter.callRelay(RecurrenceEventFilter.java:109)
	at org.openbase.jul.schedule.RecurrenceEventFilter.trigger(RecurrenceEventFilter.java:95)
	at org.openbase.jul.storage.registry.RegistrySynchronizer.lambda$new$0(RegistrySynchronizer.java:86)
	at org.openbase.jul.pattern.AbstractObservable.notifyObservers(AbstractObservable.java:244)
	at org.openbase.jul.pattern.AbstractObservable.notifyObservers(AbstractObservable.java:188)
	at org.openbase.jul.storage.registry.AbstractRegistry.notifyObservers(AbstractRegistry.java:662)
	at org.openbase.jul.storage.registry.AbstractRegistry.replaceInternalMap(AbstractRegistry.java:529)
	at org.openbase.jul.storage.registry.AbstractRegistry.replaceInternalMap(AbstractRegistry.java:496)
	at org.openbase.jul.storage.registry.RemoteRegistry.notifyRegistryUpdate(RemoteRegistry.java:75)
	at org.openbase.bco.registry.lib.com.RemoteRegistrySynchronizer.update(RemoteRegistrySynchronizer.java:99)
	at org.openbase.bco.registry.lib.com.RemoteRegistrySynchronizer.update(RemoteRegistrySynchronizer.java:42)
	at org.openbase.jul.pattern.AbstractObservable.notifyObservers(AbstractObservable.java:244)
	at org.openbase.jul.pattern.AbstractObservable.notifyObservers(AbstractObservable.java:188)
	at org.openbase.jul.extension.rsb.com.RSBRemoteService.applyDataUpdate(RSBRemoteService.java:1152)
	at org.openbase.jul.extension.rsb.com.RSBRemoteService.access$900(RSBRemoteService.java:72)
	at org.openbase.jul.extension.rsb.com.RSBRemoteService$InternalUpdateHandler.internalNotify(RSBRemoteService.java:1087)
	at rsb.eventprocessing.SingleThreadEventReceivingStrategy$DispatchThread.run(SingleThreadEventReceivingStrategy.java:92)
12:27:57.162 [Thread-12176] ERROR o.o.j.s.RecurrenceEventFilter =====================================
12:27:57.165 [Thread-12298] INFO  o.o.b.r.l.r.LocationRegistryRemote Remote connection to Controller[/test/sebastian/registry/location/] was detached because the controller shutdown was initiated.
12:27:57.166 [Thread-12302] INFO  o.o.b.r.s.r.SceneRegistryRemote Remote connection to Controller[/test/sebastian/registry/scene/] was detached because the controller shutdown was initiated.
12:27:57.168 [Thread-12305] INFO  o.o.b.r.u.r.UserRegistryRemote Remote connection to Controller[/test/sebastian/registry/user/] was detached because the controller shutdown was initiated.
12:27:57.170 [Thread-12294] INFO  o.o.b.r.d.r.DeviceRegistryRemote Remote connection to Controller[/test/sebastian/registry/device/] was detached because the controller shutdown was initiated.
12:27:57.171 [Thread-12288] INFO  o.o.b.r.a.r.AgentRegistryRemote Remote connection to Controller[/test/sebastian/registry/agent/] was detached because the controller shutdown was initiated.
12:27:57.172 [Thread-12291] INFO  o.o.b.r.a.r.AppRegistryRemote Remote connection to Controller[/test/sebastian/registry/app/] was detached because the controller shutdown was initiated.
12:27:57.172 [pool-2-thread-3] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry 100% consistency checks passed of LocationConfigRegistry after 1 applied modifications.
12:27:57.174 [Thread-12176] INFO  o.o.b.r.u.r.UnitRegistryRemote Remote connection to Controller[/test/sebastian/registry/unit/] was detached because the controller shutdown was initiated.
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.975 sec <<< FAILURE! - in org.openbase.bco.manager.device.test.DalRegisterDeviceTest
testRegisterDeviceWhileRunning(org.openbase.bco.manager.device.test.DalRegisterDeviceTest)  Time elapsed: 0.073 sec  <<< ERROR!
org.openbase.jul.exception.NotAvailableException: Entry[c7aa2763-249c-443f-8159-62400b0603b7]] is not available! Nearest neighbor is UnitConfig[F_MotionSensor_Device_Stairway] or UnitConfig[F_MotionSensor_Device_Heaven].
	at org.openbase.bco.manager.device.test.DalRegisterDeviceTest.testRegisterDeviceWhileRunning(DalRegisterDeviceTest.java:71)


Results :

Tests in error: 
  DalRegisterDeviceTest.testRegisterDeviceWhileRunning:71 » NotAvailable Entry[c...

Tests run: 45, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] BCO Manager ........................................ SUCCESS [  3.516 s]
[INFO] BCO Manager Device ................................. SUCCESS [  1.812 s]
[INFO] BCO Manager Device Library ......................... SUCCESS [  2.872 s]
[INFO] BCO Manager Device Core ............................ SUCCESS [  3.235 s]
[INFO] BCO Manager Device Remote .......................... SUCCESS [  2.716 s]
[INFO] BCO Manager Device Test ............................ FAILURE [ 43.619 s]
[INFO] BCO Manager Device Bindings ........................ SKIPPED
[INFO] BCO Manager Device Binding OpenHAB ................. SKIPPED
[INFO] BCO Manager Location ............................... SKIPPED
[INFO] BCO Manager Location Library ....................... SKIPPED
[INFO] BCO Manager Location Remote ........................ SKIPPED
[INFO] BCO Manager Location Bindings ...................... SKIPPED
[INFO] BCO Manager Location Binding OpenHAB ............... SKIPPED
[INFO] BCO Manager Location Core .......................... SKIPPED
[INFO] BCO Manager Location Test .......................... SKIPPED
[INFO] BCO Manager Scene .................................. SKIPPED
[INFO] BCO Manager Scene Library .......................... SKIPPED
[INFO] BCO Manager Scene Core ............................. SKIPPED
[INFO] BCO Manager Scene Remote ........................... SKIPPED
[INFO] BCO Manager Scene Test ............................. SKIPPED
[INFO] BCO Manager Scene Visualisation .................... SKIPPED
[INFO] BCO Manager Scene Bindings ......................... SKIPPED
[INFO] BCO Manager Scene Binding OpenHAB .................. SKIPPED
[INFO] BCO Manager Agent .................................. SKIPPED
[INFO] BCO Manager Agent Library .......................... SKIPPED
[INFO] BCO Manager Agent Remote ........................... SKIPPED
[INFO] BCO Manager Agent Bindings ......................... SKIPPED
[INFO] BCO Manager Agent Binding OpenHAB .................. SKIPPED
[INFO] BCO Manager Agent Core ............................. SKIPPED
[INFO] BCO Manager Agent Test ............................. SKIPPED
[INFO] BCO Manager App .................................... SKIPPED
[INFO] BCO Manager App Library ............................ SKIPPED
[INFO] BCO Manager App Remote ............................. SKIPPED
[INFO] BCO Manager App Bindings ........................... SKIPPED
[INFO] BCO Manager App Binding OpenHAB .................... SKIPPED
[INFO] BCO Manager App Core ............................... SKIPPED
[INFO] BCO Manager App Test ............................... SKIPPED
[INFO] BCO Manager User ................................... SKIPPED
[INFO] BCO Manager User Library ........................... SKIPPED
[INFO] BCO Manager User Core .............................. SKIPPED
[INFO] BCO Manager User Remote ............................ SKIPPED
[INFO] BCO Manager User Test .............................. SKIPPED
[INFO] BCO Manager Utility ................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 58.035 s
[INFO] Finished at: 2017-07-24T12:28:00+02:00
[INFO] Final Memory: 56M/545M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project manager.device.test: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/sebastian/workspace/openbase/bco/bco.manager/device-manager/test/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :manager.device.test

```

**Comment by pLeminoq** [comment]
I am not sure if this can happen anymore after the changes since then. Reopen if this happens again.
