### ISSUE TITLE
Test Shutdown failed

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.manager#49]
<pre>
14:06:24.046 [ShutdownDeamon[UnitRemotePool]] ERROR o.o.b.r.u.r.CachedUnitRegistryRemote ═╦═⚀ Could not start cached unit registry remote!
14:06:24.046 [ShutdownDeamon[UnitRemotePool]] ERROR o.o.b.r.u.r.CachedUnitRegistryRemote  ╚════⚀ Shutdown in progress
14:06:24.046 [ShutdownDeamon[UnitRemotePool]] ERROR o.o.b.r.u.r.CachedUnitRegistryRemote =====================================
14:06:24.047 [ShutdownDeamon[UnitRemotePool]] ERROR o.o.b.r.u.r.CachedUnitRegistryRemote Could not start cached unit registry remote!
org.openbase.jul.exception.CouldNotPerformException: Could not start cached unit registry remote!
	at org.openbase.bco.registry.unit.remote.CachedUnitRegistryRemote.getRegistry(CachedUnitRegistryRemote.java:99)
	at org.openbase.bco.registry.remote.Registries.getUnitRegistry(Registries.java:54)
	at org.openbase.bco.dal.remote.unit.AbstractUnitRemote.shutdown(AbstractUnitRemote.java:754)
	at org.openbase.bco.dal.remote.unit.Units$1.lambda$shutdown$0(Units.java:206)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583)
	at org.openbase.bco.dal.remote.unit.Units$1.shutdown(Units.java:203)
	at org.openbase.jul.iface.Shutdownable$ShutdownDeamon.run(Shutdownable.java:106)
Caused by: java.lang.IllegalStateException: Shutdown in progress
	at java.lang.ApplicationShutdownHooks.add(ApplicationShutdownHooks.java:66)
	at java.lang.Runtime.addShutdownHook(Runtime.java:211)
	at org.openbase.jul.iface.Shutdownable$ShutdownDeamon.<init>(Shutdownable.java:92)
	at org.openbase.jul.iface.Shutdownable$ShutdownDeamon.<init>(Shutdownable.java:74)
	at org.openbase.jul.iface.Shutdownable.registerShutdownHook(Shutdownable.java:55)
	at org.openbase.jul.storage.registry.AbstractRegistry.<init>(AbstractRegistry.java:126)
	at org.openbase.jul.storage.registry.AbstractRegistry.<init>(AbstractRegistry.java:101)
	at org.openbase.jul.storage.registry.RemoteRegistry.<init>(RemoteRegistry.java:66)
	at org.openbase.jul.storage.registry.RemoteRegistry.<init>(RemoteRegistry.java:62)
	at org.openbase.bco.registry.lib.com.SynchronizedRemoteRegistry.<init>(SynchronizedRemoteRegistry.java:77)
	at org.openbase.bco.registry.unit.remote.UnitRegistryRemote.<init>(UnitRegistryRemote.java:89)
	at org.openbase.bco.registry.unit.remote.CachedUnitRegistryRemote.getRegistry(CachedUnitRegistryRemote.java:89)
	... 18 common frames omitted
14:06:24.047 [ShutdownDeamon[UnitRemotePool]] ERROR o.o.b.r.u.r.CachedUnitRegistryRemote =====================================
14:06:24.056 [ShutdownDeamon[UnitRemotePool]] ERROR o.o.b.r.u.r.CachedUnitRegistryRemote ═╦═⚀ Could not start cached unit registry remote!
14:06:24.056 [ShutdownDeamon[UnitRemotePool]] ERROR o.o.b.r.u.r.CachedUnitRegistryRemote  ╚════⚀ Shutdown in progress
14:06:24.056 [ShutdownDeamon[UnitRemotePool]] ERROR o.o.b.r.u.r.CachedUnitRegistryRemote =====================================
14:06:24.056 [ShutdownDeamon[UnitRemotePool]] ERROR o.o.b.r.u.r.CachedUnitRegistryRemote Could not start cached unit registry remote!
org.openbase.jul.exception.CouldNotPerformException: Could not start cached unit registry remote!
	at org.openbase.bco.registry.unit.remote.CachedUnitRegistryRemote.getRegistry(CachedUnitRegistryRemote.java:99)
	at org.openbase.bco.registry.remote.Registries.getUnitRegistry(Registries.java:54)
	at org.openbase.bco.dal.remote.unit.AbstractUnitRemote.shutdown(AbstractUnitRemote.java:754)
	at org.openbase.jul.storage.registry.RemoteControllerRegistry.clear(RemoteControllerRegistry.java:50)
	at org.openbase.jul.storage.registry.AbstractRegistry.shutdown(AbstractRegistry.java:947)
	at org.openbase.bco.dal.remote.unit.Units$1.shutdown(Units.java:214)
	at org.openbase.jul.iface.Shutdownable$ShutdownDeamon.run(Shutdownable.java:106)
Caused by: java.lang.IllegalStateException: Shutdown in progress
	at java.lang.ApplicationShutdownHooks.add(ApplicationShutdownHooks.java:66)
	at java.lang.Runtime.addShutdownHook(Runtime.java:211)
	at org.openbase.jul.iface.Shutdownable$ShutdownDeamon.<init>(Shutdownable.java:92)
	at org.openbase.jul.iface.Shutdownable$ShutdownDeamon.<init>(Shutdownable.java:74)
	at org.openbase.jul.iface.Shutdownable.registerShutdownHook(Shutdownable.java:55)
	at org.openbase.jul.storage.registry.AbstractRegistry.<init>(AbstractRegistry.java:126)
	at org.openbase.jul.storage.registry.AbstractRegistry.<init>(AbstractRegistry.java:101)
	at org.openbase.jul.storage.registry.RemoteRegistry.<init>(RemoteRegistry.java:66)
	at org.openbase.jul.storage.registry.RemoteRegistry.<init>(RemoteRegistry.java:62)
	at org.openbase.bco.registry.lib.com.SynchronizedRemoteRegistry.<init>(SynchronizedRemoteRegistry.java:77)
	at org.openbase.bco.registry.unit.remote.UnitRegistryRemote.<init>(UnitRegistryRemote.java:89)
	at org.openbase.bco.registry.unit.remote.CachedUnitRegistryRemote.getRegistry(CachedUnitRegistryRemote.java:89)
	... 6 common frames omitted
14:06:24.056 [ShutdownDeamon[UnitRemotePool]] ERROR o.o.b.r.u.r.CachedUnitRegistryRemote =====================================
14:06:27.056 [ShutdownDeamon[GlobalCachedExecutorService]] INFO  o.o.j.s.GlobalCachedExecutorService Waiting for 1 tasks to continue the shutdown.

</pre>

**Comment by pLeminoq** [comment]
Does this issue still exist?

**Comment by pLeminoq** [comment]
I thinks this issue is outdated. The AbstractRegistry does not register itself as a shutdown hook anymore in its constructor. Thus the above error should be impossible.
