### ISSUE TITLE
RSB Nullpointer during deactivate

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.manager#56]
A status notification after participant shutdown is not a good idea but the nullpointer should not occur anyway.

**Okay Exception is from 2016 :D any maybe already fixed?**

<pre>
2016-06-25 21:39:27.788 INFO  o.o.b.rsb.internal.RSBBinding[:163]- Deactivate RSBBinding...
2016-06-25 21:39:27.791 DEBUG o.o.b.r.internal.RSBBinding$1[:425]- Notify data change of [/openhab/status/]
2016-06-25 21:39:28.292 INFO  o.o.b.r.internal.RSBBinding$1[:331]- [/openhab/status/] is now OFFLINE
2016-06-25 21:39:28.293 DEBUG o.o.b.r.internal.RSBBinding$1[:336]- Notify data change of [/openhab/status/]
2016-06-25 21:39:28.314 ERROR o.o.b.r.internal.RSBBinding$1[:68]- ═╦═ Could not update communication service state in internal data object!
2016-06-25 21:39:28.314 ERROR o.o.b.r.internal.RSBBinding$1[:68]-  ╚╦═ Could not notify change of [/openhab/status/]!
2016-06-25 21:39:28.315 ERROR o.o.b.r.internal.RSBBinding$1[:68]-   ╚╦═ Could not send Event[scope=/openhab/status/, type=class rst.homeautomation.openhab.RSBBindingType$RSBBinding, metaData=MetaData[createTime = 1466883568293000, sendTime = 0, receiveTime = 0, userTimes = {}, userInfos = {}]]!
2016-06-25 21:39:28.315 ERROR o.o.b.r.internal.RSBBinding$1[:68]-    ╚══ NullPointerException
2016-06-25 21:39:28.315 ERROR o.o.b.r.internal.RSBBinding$1[:68]- =====================================
2016-06-25 21:39:28.325 ERROR o.o.b.r.internal.RSBBinding$1[:89]- Could not update communication service state in internal data object!
org.openbase.jul.exception.CouldNotPerformException: Could not update communication service state in internal data object!
        at org.openbase.jul.extension.rsb.com.RSBCommunicationService.setControllerAvailabilityState(RSBCommunicationService.java:348)
        at org.openbase.jul.extension.rsb.com.RSBCommunicationService.deactivate(RSBCommunicationService.java:287)
        at org.openhab.binding.rsb.internal.RSBBinding.deactivate(RSBBinding.java:186)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Caused by: org.openbase.jul.exception.CouldNotPerformException: Could not notify change of [/openhab/status/]!
        at org.openbase.jul.extension.rsb.com.RSBCommunicationService.setControllerAvailabilityState(RSBCommunicationService.java:345)
        at org.openbase.jul.extension.rsb.com.RSBCommunicationService.deactivate(RSBCommunicationService.java:287)
        at org.openhab.binding.rsb.internal.RSBBinding.deactivate(RSBBinding.java:186)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Caused by: org.openbase.jul.exception.CouldNotPerformException: Could not send Event[scope=/openhab/status/, type=class rst.homeautomation.openhab.RSBBindingType$RSBBinding, metaData=MetaData[createTime = 1466883568293000, sendTime = 0, receiveTime = 0, userTimes = {}, userInfos = {}]]!
        at org.openbase.jul.extension.rsb.com.RSBSynchronizedInformer.send(RSBSynchronizedInformer.java:98)
        at org.openbase.jul.extension.rsb.com.RSBCommunicationService.setControllerAvailabilityState(RSBCommunicationService.java:343)
        at org.openbase.jul.extension.rsb.com.RSBCommunicationService.deactivate(RSBCommunicationService.java:287)
        at org.openhab.binding.rsb.internal.RSBBinding.deactivate(RSBBinding.java:186)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Caused by: java.lang.NullPointerException: null
        at rsb.converter.ProtocolBufferConverter.serialize(ProtocolBufferConverter.java:74)
        at rsb.protocol.ProtocolConversion.serializeEventData(ProtocolConversion.java:152)
        at rsb.transport.spread.SpreadOutConnector.push(SpreadOutConnector.java:210)
        at rsb.eventprocessing.DefaultOutRouteConfigurator.publishSync(DefaultOutRouteConfigurator.java:91)
        at rsb.Informer$StateActive.send(Informer.java:186)
        at rsb.Informer.publish(Informer.java:306)
2016-06-25 21:39:28.325 ERROR o.o.b.r.internal.RSBBinding$1[:68]- =====================================
2016-06-25 21:39:28.421 DEBUG o.o.b.r.internal.RSBActivator[:57]- rsb binding has been stopped.
</pre>

**Comment by pLeminoq** [comment]
Did this occur again since then? Else I think it can be closed.
