### ISSUE TITLE
Fix Device Manager test failures.

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.manager#62]
<pre>
[INFO] 14:40:56.379 [pool-1-thread-88] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry [DalUnitConfigRegistry]: 100% consistency checks passed of DalUnitConfigRegistry after 13 applied modifications.
[INFO] 14:40:56.379 [pool-1-thread-88] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry [LocationConfigRegistry]: 0% of max consistency checks passed of LocationConfigRegistry after 1 applied modifications.
[INFO] 14:40:56.380 [pool-1-thread-88] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry [LocationConfigRegistry]: 100% consistency checks passed of LocationConfigRegistry after 1 applied modifications.
[INFO] 14:40:56.385 [pool-1-thread-88] INFO  o.o.j.s.r.ProtoBufFileSynchronizedRegistry [DeviceConfigRegistry]: Update UnitConfig[SimpleDevice_0]...
[INFO] 14:41:11.204 [Time-limited test] ERROR o.o.b.m.d.t.DalRegisterDeviceTest ═══⚀ InterruptedException
[INFO] 14:41:11.204 [Time-limited test] ERROR o.o.b.m.d.t.DalRegisterDeviceTest =====================================
[INFO] 14:41:11.206 [Time-limited test] ERROR o.o.b.m.d.t.DalRegisterDeviceTest InterruptedException
[INFO] java.lang.InterruptedException: null
[INFO] 	at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:404)
[INFO] 	at java.util.concurrent.FutureTask.get(FutureTask.java:191)
[INFO] 	at org.openbase.jul.schedule.AbstractSynchronizationFuture.get(AbstractSynchronizationFuture.java:142)
[INFO] 	at org.openbase.bco.manager.device.test.DalRegisterDeviceTest.testRegisteringManyDevices(DalRegisterDeviceTest.java:214)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[INFO] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO] 	at java.lang.reflect.Method.invoke(Method.java:498)
[INFO] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
[INFO] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[INFO] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
[INFO] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[INFO] 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
[INFO] 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
[INFO] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[INFO] 	at java.lang.Thread.run(Thread.java:748)
[INFO] 14:41:11.206 [Time-limited test] ERROR o.o.b.m.d.t.DalRegisterDeviceTest =====================================
</pre>

**Comment by DivineThreepwood** [comment]
The registerUnitConfig remote methode can only throw an InterruptedException if the the remote tasks (register unit config) takes to long right? At least a shutdown was not initialized. So maybe this is issue is caused as well by the deadlock reported in openbase/bco.dal#104?

**Comment by DivineThreepwood** [comment]
Seems to be solved with commit openbase/jul@40ee3a2 and openbase/bco.dal@ee83a7a
Let's keep this issue at least for one week in the review section so it can be reopen if it occurs again.

**Comment by DivineThreepwood** [comment]
Fix confirmed.
