### ISSUE TITLE
Travis build failure because MockRegistry reinitialization fails

### ISSUE THREAD

**Issue by pLeminoq** [openbase/bco.manager#66]
Travis build https://travis-ci.org/openbase/bco.manager/builds/377663216:

<pre>
10:27:59.150 [Thread-12584] INFO  o.o.b.r.d.r.DeviceRegistryRemote Remote connection to Controller[/test/travis/registry/device/] was detached because the controller shutdown was initiated.
10:27:59.155 [Thread-12582] INFO  o.o.b.r.a.r.AgentRegistryRemote Remote connection to Controller[/test/travis/registry/agent/] was detached because the controller shutdown was initiated.
10:27:59.159 [Thread-12583] INFO  o.o.b.r.a.r.AppRegistryRemote Remote connection to Controller[/test/travis/registry/app/] was detached because the controller shutdown was initiated.
10:27:59.168 [main] ERROR o.o.b.d.t.AbstractBCOTest â•â•¦â•âš€ Could not instantiate MockRegistry!
10:27:59.168 [main] ERROR o.o.b.d.t.AbstractBCOTest  â•šâ•â•â•¦â•âš€ Could not reinitialize CachedUnitRegistryRemote!
10:27:59.168 [main] ERROR o.o.b.d.t.AbstractBCOTest     â•šâ•â•â•â•âš€ TimeoutException
10:27:59.168 [main] ERROR o.o.b.d.t.AbstractBCOTest =====================================
10:27:59.169 [main] ERROR o.o.b.d.t.AbstractBCOTest Could not instantiate MockRegistry!
org.openbase.jul.exception.InstantiationException: Could not instantiate MockRegistry!
	at org.openbase.bco.registry.mock.MockRegistry.<init>(MockRegistry.java:468)
	at org.openbase.bco.registry.mock.MockRegistryHolder.newMockRegistry(MockRegistryHolder.java:43)
	at org.openbase.bco.dal.test.AbstractBCOTest.setUpClass(AbstractBCOTest.java:44)
	at org.openbase.bco.manager.device.test.AbstractBCODeviceManagerTest.setUpClass(AbstractBCODeviceManagerTest.java:45)
	at org.openbase.bco.manager.device.test.remote.unit.DimmableLightRemoteTest.setUpClass(DimmableLightRemoteTest.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:369)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:275)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:239)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:160)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
Caused by: org.openbase.jul.exception.CouldNotPerformException: Could not reinitialize CachedUnitRegistryRemote!
	at org.openbase.bco.registry.unit.remote.CachedUnitRegistryRemote.reinitialize(CachedUnitRegistryRemote.java:68)
	at org.openbase.bco.registry.remote.Registries.reinitialize(Registries.java:341)
	at org.openbase.bco.registry.mock.MockRegistry.<init>(MockRegistry.java:419)
	... 22 common frames omitted
Caused by: java.util.concurrent.TimeoutException: null
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at org.openbase.bco.registry.unit.remote.CachedUnitRegistryRemote.reinitialize(CachedUnitRegistryRemote.java:66)
	... 24 common frames omitted
10:27:59.169 [main] ERROR o.o.b.d.t.AbstractBCOTest =====================================
10:27:59.169 [main] ERROR o.o.b.m.d.t.AbstractBCODeviceManagerTest â•â•¦â•âš€ Could not instantiate MockRegistry!
10:27:59.169 [main] ERROR o.o.b.m.d.t.AbstractBCODeviceManagerTest  â•šâ•â•â•¦â•âš€ Could not reinitialize CachedUnitRegistryRemote!
10:27:59.169 [main] ERROR o.o.b.m.d.t.AbstractBCODeviceManagerTest     â•šâ•â•â•â•âš€ TimeoutException
10:27:59.170 [main] ERROR o.o.b.m.d.t.AbstractBCODeviceManagerTest =====================================
10:27:59.171 [main] ERROR o.o.b.m.d.t.AbstractBCODeviceManagerTest Could not instantiate MockRegistry!
org.openbase.jul.exception.InstantiationException: Could not instantiate MockRegistry!
	at org.openbase.bco.registry.mock.MockRegistry.<init>(MockRegistry.java:468)
	at org.openbase.bco.registry.mock.MockRegistryHolder.newMockRegistry(MockRegistryHolder.java:43)
	at org.openbase.bco.dal.test.AbstractBCOTest.setUpClass(AbstractBCOTest.java:44)
at org.openbase.bco.manager.device.test.AbstractBCODeviceManagerTest.setUpClass(AbstractBCODeviceManagerTest.java:45)
	at org.openbase.bco.manager.device.test.remote.unit.DimmableLightRemoteTest.setUpClass(DimmableLightRemoteTest.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:369)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:275)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:239)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:160)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
Caused by: org.openbase.jul.exception.CouldNotPerformException: Could not reinitialize CachedUnitRegistryRemote!
	at org.openbase.bco.registry.unit.remote.CachedUnitRegistryRemote.reinitialize(CachedUnitRegistryRemote.java:68)
	at org.openbase.bco.registry.remote.Registries.reinitialize(Registries.java:341)
	at org.openbase.bco.registry.mock.MockRegistry.<init>(MockRegistry.java:419)
	... 22 common frames omitted
Caused by: java.util.concurrent.TimeoutException: null
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at org.openbase.bco.registry.unit.remote.CachedUnitRegistryRemote.reinitialize(CachedUnitRegistryRemote.java:66)
	... 24 common frames omitted
</pre>

**Comment by DivineThreepwood** [comment]
fixed some time ago
