### ISSUE TITLE
bco.openhab session expires after some days

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.manager#70]
* the relogin seems not to work for bco.openhab 
* maybe the exception is not correctly handled on remote site?

<pre>
23:48:16.349 [pool-1-thread-637] ERROR o.o.b.a.l.AuthenticatedServerManager ═══⚀ Your session has expired!
23:48:16.349 [pool-1-thread-637] ERROR o.o.b.a.l.AuthenticatedServerManager =====================================
23:48:16.382 [pool-1-thread-605] ERROR o.o.b.d.c.l.u.ColorableLightController ═╦═⚀ Could not invoke Method[Class requestDataAuthenticated(TicketAuthenticatorWrapper)] of ColorableLightController[COLORABLE_LIGHT[Decken Lampe 2]]!
23:48:16.382 [pool-1-thread-605] ERROR o.o.b.d.c.l.u.ColorableLightController  ╚════⚀ Your session has expired!
23:48:16.382 [pool-1-thread-605] ERROR o.o.b.d.c.l.u.ColorableLightController =====================================
Jan 30, 2019 11:48:16 PM rsb.patterns.LocalMethod prepareErrorReply
WARNING: Exception during method invocation in participant: /chillerstrasse/badezimmer/colorablelight/deckenlampe2/ctrl/requestDataAuthenticated/. Exception message: org.openbase.jul.exception.CouldNotPerformException: Could not invoke Method[Class requestDataAuthenticated(TicketAuthenticatorWrapper)] of ColorableLightController[COLORABLE_LIGHT[Decken Lampe 2]]!
23:48:31.355 [pool-1-thread-533] ERROR o.o.b.a.l.AuthenticatedServerManager ═══⚀ Your session has expired!
23:48:31.356 [pool-1-thread-533] ERROR o.o.b.a.l.AuthenticatedServerManager =====================================
23:48:31.359 [pool-1-thread-488] ERROR o.o.b.d.c.l.u.ColorableLightController ═╦═⚀ Could not invoke Method[Class requestDataAuthenticated(TicketAuthenticatorWrapper)] of ColorableLightController[COLORABLE_LIGHT[Decken Lampe 2]]!
23:48:31.360 [pool-1-thread-488] ERROR o.o.b.d.c.l.u.ColorableLightController  ╚════⚀ Your session has expired!
23:48:31.360 [pool-1-thread-488] ERROR o.o.b.d.c.l.u.ColorableLightController =====================================
Jan 30, 2019 11:48:31 PM rsb.patterns.LocalMethod prepareErrorReply
WARNING: Exception during method invocation in participant: /chillerstrasse/badezimmer/colorablelight/deckenlampe2/ctrl/requestDataAuthenticated/. Exception message: org.openbase.jul.exception.CouldNotPerformException: Could not invoke Method[Class requestDataAuthenticated(TicketAuthenticatorWrapper)] of ColorableLightController[COLORABLE_LIGHT[Decken Lampe 2]]!
23:48:46.357 [pool-1-thread-510] ERROR o.o.b.a.l.AuthenticatedServerManager ═══⚀ Your session has expired!
23:48:46.357 [pool-1-thread-510] ERROR o.o.b.a.l.AuthenticatedServerManager =====================================
23:48:46.359 [pool-1-thread-605] ERROR o.o.b.d.c.l.u.ColorableLightController ═╦═⚀ Could not invoke Method[Class requestDataAuthenticated(TicketAuthenticatorWrapper)] of ColorableLightController[COLORABLE_LIGHT[Decken Lampe 2]]!
23:48:46.359 [pool-1-thread-605] ERROR o.o.b.d.c.l.u.ColorableLightController  ╚════⚀ Your session has expired!
23:48:46.359 [pool-1-thread-605] ERROR o.o.b.d.c.l.u.ColorableLightController =====================================
</pre>

**Comment by DivineThreepwood** [comment]
even after a complete restart, the error occurs again. This time at the bco core runtime.
<pre>
02:30:30.022 [pool-1-thread-91] ERROR o.o.b.r.t.c.TemplateRegistryController ═╦═⚀ Could not invoke Method[Class requestDataAuthenticated(TicketAuthenticatorWrapper)] of TemplateRegistryController[/registry/template/status/]!
02:30:30.022 [pool-1-thread-91] ERROR o.o.b.r.t.c.TemplateRegistryController  ╚════⚀ Your session has expired!
02:30:30.023 [pool-1-thread-91] ERROR o.o.b.r.t.c.TemplateRegistryController =====================================
02:30:30.024 [pool-1-thread-91] ERROR o.o.b.r.t.c.TemplateRegistryController Could not invoke Method[Class requestDataAuthenticated(TicketAuthenticatorWrapper)] of TemplateRegistryController[/registry/template/status/]!
org.openbase.jul.exception.CouldNotPerformException: Could not invoke Method[Class requestDataAuthenticated(TicketAuthenticatorWrapper)] of TemplateRegistryController[/registry/template/status/]!
        at org.openbase.jul.extension.rsb.com.RPCHelper.lambda$registerMethod$1(RPCHelper.java:166)
        at rsb.patterns.LocalMethod.internalNotify(LocalMethod.java:121)
        at org.openbase.jul.extension.rsb.com.strategy.ThreadPoolUnorderedEventReceivingStrategy$DispatchTask.call(ThreadPoolUnorderedEventReceivingStrategy.java:198)
        at org.openbase.jul.extension.rsb.com.strategy.ThreadPoolUnorderedEventReceivingStrategy$DispatchTask.call(ThreadPoolUnorderedEventReceivingStrategy.java:169)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.reflect.InvocationTargetException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:206)
        at org.openbase.jul.extension.rsb.com.RPCHelper.lambda$registerMethod$1(RPCHelper.java:137)
        ... 7 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.openbase.jul.extension.rsb.com.RPCHelper.lambda$null$0(RPCHelper.java:134)
        ... 4 common frames omitted
Caused by: org.openbase.bco.authentication.lib.exception.SessionExpiredException: Your session has expired!
        at org.openbase.bco.authentication.lib.AuthenticationServerHandler.validateTicket(AuthenticationServerHandler.java:183)
        at org.openbase.bco.authentication.lib.AuthenticatedServerManager.verifyClientServerTicket(AuthenticatedServerManager.java:141)
        at org.openbase.bco.authentication.lib.com.AbstractAuthenticatedControllerServer.requestDataAuthenticated(AbstractAuthenticatedControllerServer.java:103)
        ... 9 common frames omitted
02:30:30.025 [pool-1-thread-91] ERROR o.o.b.r.t.c.TemplateRegistryController =====================================
Jan 31, 2019 2:30:30 AM rsb.patterns.LocalMethod prepareErrorReply
WARNING: Exception during method invocation in participant: /registry/template/ctrl/requestDataAuthenticated/. Exception message: org.openbase.jul.exception.CouldNotPerformException: Could not invoke Method[Class requestDataAuthenticated(TicketAuthenticatorWrapper)] of TemplateRegistryController[/registry/template/status/]!
02:30:34.754 [pool-1-thread-16] ERROR o.o.b.a.l.AuthenticatedServerManager ═══⚀ Your session has expired!
02:30:34.757 [pool-1-thread-16] ERROR o.o.b.a.l.AuthenticatedServerManager =====================================
02:30:34.761 [pool-1-thread-16] ERROR o.o.b.a.l.AuthenticatedServerManager Your session has expired!
org.openbase.bco.authentication.lib.exception.SessionExpiredException: Your session has expired!
        at org.openbase.bco.authentication.lib.AuthenticationServerHandler.validateTicket(AuthenticationServerHandler.java:183)
        at org.openbase.bco.authentication.lib.AuthenticatedServerManager.verifyClientServerTicket(AuthenticatedServerManager.java:141)
        at org.openbase.bco.authentication.lib.com.AbstractAuthenticatedControllerServer.requestDataAuthenticated(AbstractAuthenticatedControllerServer.java:103)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.openbase.jul.extension.rsb.com.RPCHelper.lambda$null$0(RPCHelper.java:134)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
02:30:34.764 [pool-1-thread-16] ERROR o.o.b.a.l.AuthenticatedServerManager =====================================
02:30:34.767 [pool-1-thread-49] ERROR o.o.b.r.a.c.ActivityRegistryController ═╦═⚀ Could not invoke Method[Class requestDataAuthenticated(TicketAuthenticatorWrapper)] of ActivityRegistryController[/registry/activity/status/]!
02:30:34.767 [pool-1-thread-49] ERROR o.o.b.r.a.c.ActivityRegistryController  ╚════⚀ Your session has expired!
02:30:34.767 [pool-1-thread-49] ERROR o.o.b.r.a.c.ActivityRegistryController =====================================
02:30:34.769 [pool-1-thread-49] ERROR o.o.b.r.a.c.ActivityRegistryController Could not invoke Method[Class requestDataAuthenticated(TicketAuthenticatorWrapper)] of ActivityRegistryController[/registry/activity/status/]!
org.openbase.jul.exception.CouldNotPerformException: Could not invoke Method[Class requestDataAuthenticated(TicketAuthenticatorWrapper)] of ActivityRegistryController[/registry/activity/status/]!
        at org.openbase.jul.extension.rsb.com.RPCHelper.lambda$registerMethod$1(RPCHelper.java:166)
        at rsb.patterns.LocalMethod.internalNotify(LocalMethod.java:121)
        at org.openbase.jul.extension.rsb.com.strategy.ThreadPoolUnorderedEventReceivingStrategy$DispatchTask.call(ThreadPoolUnorderedEventReceivingStrategy.java:198)
        at org.openbase.jul.extension.rsb.com.strategy.ThreadPoolUnorderedEventReceivingStrategy$DispatchTask.call(ThreadPoolUnorderedEventReceivingStrategy.java:169)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.reflect.InvocationTargetException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:206)
        at org.openbase.jul.extension.rsb.com.RPCHelper.lambda$registerMethod$1(RPCHelper.java:137)
        ... 7 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.openbase.jul.extension.rsb.com.RPCHelper.lambda$null$0(RPCHelper.java:134)
        ... 4 common frames omitted
Caused by: org.openbase.bco.authentication.lib.exception.SessionExpiredException: Your session has expired!
        at org.openbase.bco.authentication.lib.AuthenticationServerHandler.validateTicket(AuthenticationServerHandler.java:183)
        at org.openbase.bco.authentication.lib.AuthenticatedServerManager.verifyClientServerTicket(AuthenticatedServerManager.java:141)
        at org.openbase.bco.authentication.lib.com.AbstractAuthenticatedControllerServer.requestDataAuthenticated(AbstractAuthenticatedControllerServer.java:103)
        ... 9 common frames omitted
02:30:34.770 [pool-1-thread-49] ERROR o.o.b.r.a.c.ActivityRegistryController =====================================
</pre>

**Comment by DivineThreepwood** [comment]
has been fixed by @pLeminoq 
the admin session was not auto extended. We still need a way to print the openhab credentials via the bco consol, but that's another issue.

**Comment by DivineThreepwood** [comment]
close me when error not reoccur within the next week.

**Comment by DivineThreepwood** [comment]
seems to be fixed.
