### ISSUE TITLE
Openhab device manager - Jetty Bad Request

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.manager#71]
Print some more information about the context which was send to openhab.
Sometimes there seems something wrong with the used data syntax:

<pre>
19:45:41.416 [pool-1-thread-528] WARN  o.o.b.d.o.m.s.PowerStateServiceImpl ═╦═⚄ Some command classes could not be used to apply the state:
19:45:41.416 [pool-1-thread-528] WARN  o.o.b.d.o.m.s.PowerStateServiceImpl  ╠══╦═⚀ Could not post value[0,0,0] on sub-URL[items/ColorableLight_19__PowerStateService]
19:45:41.416 [pool-1-thread-528] WARN  o.o.b.d.o.m.s.PowerStateServiceImpl  ║  ╚════⚀ Response returned with errorCode[400] and error message[<html><head><meta http-equiv="Content-Type" content="text/html;charset=utf-8"/><title>Error 400 Bad Request</title></head><body><h2>HTTP ERROR 400</h2><p>Problem accessing /rest/items/ColorableLight_19__PowerStateService. Reason:<pre>    Bad Request</pre></p><hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.11.v20180605</a><hr/></body></html>]
19:45:41.416 [pool-1-thread-528] WARN  o.o.b.d.o.m.s.PowerStateServiceImpl  ╚══╦═⚀ Could not post value[0] on sub-URL[items/ColorableLight_19__PowerStateService]
19:45:41.416 [pool-1-thread-528] WARN  o.o.b.d.o.m.s.PowerStateServiceImpl     ╚════⚀ Response returned with errorCode[400] and error message[<html><head><meta http-equiv="Content-Type" content="text/html;charset=utf-8"/><title>Error 400 Bad Request</title></head><body><h2>HTTP ERROR 400</h2><p>Problem accessing /rest/items/ColorableLight_19__PowerStateService. Reason:<pre>    Bad Request</pre></p><hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.11.v20180605</a><hr/></body></html>]
19:45:41.416 [pool-1-thread-528] WARN  o.o.b.d.o.m.s.PowerStateServiceImpl =====================================
19:45:41.416 [pool-1-thread-528] WARN  o.o.b.d.o.m.s.PowerStateServiceImpl Some command classes could not be used to apply the state:
org.openbase.jul.exception.MultiException: Some command classes could not be used to apply the state:
        at org.openbase.jul.exception.MultiException.checkAndThrow(MultiException.java:82)
        at org.openbase.bco.device.openhab.manager.service.OpenHABService.setState(OpenHABService.java:131)
        at org.openbase.bco.device.openhab.manager.service.PowerStateServiceImpl.setPowerState(PowerStateServiceImpl.java:43)
        at sun.reflect.GeneratedMethodAccessor541.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.openbase.bco.dal.lib.layer.service.Services.invokeServiceMethod(Services.java:417)
        at org.openbase.bco.dal.lib.layer.service.Services.invokeServiceMethod(Services.java:412)
        at org.openbase.bco.dal.lib.layer.service.Services.invokeOperationServiceMethod(Services.java:440)
        at org.openbase.bco.dal.control.layer.unit.AbstractUnitController.performOperationService(AbstractUnitController.java:1738)
        at org.openbase.bco.dal.control.action.ActionImpl.lambda$execute$0(ActionImpl.java:245)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.openbase.jul.exception.CouldNotPerformException: Could not post value[0,0,0] on sub-URL[items/ColorableLight_19__PowerStateService]
        at org.openbase.bco.device.openhab.OpenHABRestCommunicator.post(OpenHABRestCommunicator.java:409)
        at org.openbase.bco.device.openhab.OpenHABRestCommunicator.postCommand(OpenHABRestCommunicator.java:292)
        at org.openbase.bco.device.openhab.manager.service.OpenHABService.setState(OpenHABService.java:116)
        ... 13 common frames omitted
Caused by: org.openbase.jul.exception.CouldNotPerformException: Response returned with errorCode[400] and error message[<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 400 Bad Request</title>
</head>
<body><h2>HTTP ERROR 400</h2>
<p>Problem accessing /rest/items/ColorableLight_19__PowerStateService. Reason:
<pre>    Bad Request</pre></p><hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.11.v20180605</a><hr/>

</body>
</html>
]
        at org.openbase.bco.device.openhab.OpenHABRestCommunicator.validateResponse(OpenHABRestCommunicator.java:424)
        at org.openbase.bco.device.openhab.OpenHABRestCommunicator.post(OpenHABRestCommunicator.java:407)
        ... 15 common frames omitted
19:45:41.417 [pool-1-thread-528] WARN  o.o.b.d.o.m.s.PowerStateServiceImpl =====================================
</pre>

**Comment by DivineThreepwood** [comment]
targets openhab 2 therefore the ticket will be closed
