### ISSUE TITLE
Duplicate device registration for thing if device is disabled

### ISSUE THREAD

**Issue by pLeminoq** [openbase/bco.manager#79]
```
org.openbase.jul.exception.CouldNotPerformException: Initial sync failed!                                                                                                                                  
        at org.openbase.jul.storage.registry.AbstractSynchronizer.activate(AbstractSynchronizer.java:122)                                                                                                  
        at org.openbase.bco.device.openhab.registry.synchronizer.ThingDeviceUnitSynchronization.activate(ThingDeviceUnitSynchronization.java:69)                                                           
        at org.openbase.bco.device.openhab.registry.OpenHABConfigSynchronizer.activate(OpenHABConfigSynchronizer.java:77)                                                                                  
        at org.openbase.jul.pattern.launch.AbstractLauncher.lambda$launch$0(AbstractLauncher.java:194)                                                                                                     
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)                                                                                                                              
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)                                                                                                       
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)                                                                                                       
        at java.base/java.lang.Thread.run(Thread.java:834)                                                                                                                                                 
Caused by: org.openbase.jul.exception.CouldNotPerformException: Entry registry sync failed!                                                                                                                
        at org.openbase.jul.storage.registry.AbstractSynchronizer.internalSync(AbstractSynchronizer.java:285)                                                                                              
        at org.openbase.jul.storage.registry.AbstractSynchronizer.activate(AbstractSynchronizer.java:118)                                                                                                  
        ... 7 common frames omitted                                                                                                                                                                        
Caused by: org.openbase.jul.exception.MultiException: Could not sync all entries!                                                                                                                          
        at org.openbase.jul.exception.MultiException.checkAndThrow(MultiException.java:82)                                                                                                                 
        at org.openbase.jul.storage.registry.AbstractSynchronizer.internalSync(AbstractSynchronizer.java:274)                                                                                              
        ... 8 common frames omitted                                                                                                                                                                        
Caused by: org.openbase.jul.exception.MultiException: Could not register 1 entries!                                                                                                                        
        at org.openbase.jul.exception.MultiException.checkAndThrow(MultiException.java:82)                                                                                                                 
        at org.openbase.jul.storage.registry.AbstractSynchronizer.internalSync(AbstractSynchronizer.java:269)                                                                                              
        ... 8 common frames omitted                                                                                                                                                                        
Caused by: org.openbase.jul.exception.CouldNotPerformException: Could not register device for thing[zwave:fibaro_fgdw002_00_000]                                                                           
        at org.openbase.bco.device.openhab.registry.synchronizer.ThingDeviceUnitSynchronization.registerDevice(ThingDeviceUnitSynchronization.java:232)                                                    
        at org.openbase.bco.device.openhab.registry.synchronizer.ThingDeviceUnitSynchronization.register(ThingDeviceUnitSynchronization.java:109)                                                          
        at org.openbase.bco.device.openhab.registry.synchronizer.ThingDeviceUnitSynchronization.register(ThingDeviceUnitSynchronization.java:60)                                                           
        at org.openbase.jul.storage.registry.AbstractSynchronizer.registerInternal(AbstractSynchronizer.java:318)                                                                                          
        at org.openbase.jul.storage.registry.AbstractSynchronizer.internalSync(AbstractSynchronizer.java:211)                                                                                              
        ... 8 common frames omitted                                                                                                                                                                        
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: org.openbase.jul.extension.rsb.com.exception.RSBResolvedException: Re
mote task failed!                                                                                                                                                                                          
        at org.openbase.jul.pattern.CompletableFutureLite.get(CompletableFutureLite.java:162)                                                                                                              
        at org.openbase.jul.schedule.ResultProcessingFuture.get(ResultProcessingFuture.java:104)                                                                                                           
        at org.openbase.bco.authentication.lib.future.ReLoginFuture.get(ReLoginFuture.java:91)
        at org.openbase.bco.authentication.lib.future.AbstractAuthenticationFuture.get(AbstractAuthenticationFuture.java:162)
        at org.openbase.bco.device.openhab.registry.synchronizer.ThingDeviceUnitSynchronization.registerDevice(ThingDeviceUnitSynchronization.java:225)
        ... 12 common frames omitted
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: org.openbase.jul.extension.rsb.com.exception.RSBResolvedException: Remote task failed!
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at org.openbase.jul.schedule.ResultProcessingFuture.get(ResultProcessingFuture.java:92)
        ... 15 common frames omitted
```

**Comment by DivineThreepwood** [comment]
fixed and tested by handling even disabled devices and by fixing the LabelProcessor.compare method by formatting the label as bco would do it.
